spring.application.name=sb-ecom

#spring.h2.console.enabled=true
spring.datasource.url=jdbc:mysql://localhost:3306/eCommerce
spring.datasource.username=root
spring.datasource.password=JOp97)#?6nmu


project.image=images/
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.app.expiration=86400000
spring.app.jwtSecretKey=yourSecret63738mynameforward874jdh992db2bbdbdh03efjnnns292is
spring.app.jwtCookieName=springBootECom