spring.application.name=sb-ecom

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test


project.image=images/
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

#spring.jpa.hibernate.ddl-auto=update


spring.app.expiration=86400000
spring.app.jwtSecretKey=yourSecret63738mynameforward874jdh992db2bbdbdh03efjnnns292is